"""Reading a scatter plot — help with interpretation, built from the numbers.

The reading is deterministic prose assembled from the computed statistics:
direction and strength of the association, what the slope means in the data's
own units, whether the slope is distinguishable from zero, and the caveats
that apply to *this* plot. Nothing here is generated by a model, so the
sentences can be pinned exactly.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from app.services.analysis_executor import MAX_SCATTER_POINTS, execute_spec
from app.services.analysis_interpretation import (
    SIGNIFICANCE_LEVEL,
    SMALL_SAMPLE,
    interpret_scatter,
    strength_of,
)


def _reading(df: pd.DataFrame, **params):
    spec = {
        "operations": [
            {"op": "scatter_with_fit", "label": "T", "params": {"x": "x", "y": "y", **params}}
        ]
    }
    return interpret_scatter(execute_spec(df, spec)[0])


def _linear(n: int, slope: float, noise: float, seed: int = 0) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    x = np.arange(n, dtype=float)
    return pd.DataFrame({"x": x, "y": slope * x + rng.normal(0, noise, n)})


class TestStrengthBands:
    @pytest.mark.parametrize(
        "r,expected",
        [
            (0.0, "negligible"),
            (0.09, "negligible"),
            (0.1, "weak"),
            (-0.29, "weak"),
            (0.3, "moderate"),
            (0.49, "moderate"),
            (0.5, "strong"),
            (-0.95, "strong"),
        ],
    )
    def test_uses_cohen_conventions_on_the_absolute_value(self, r, expected):
        assert strength_of(r) == expected

    def test_an_uncomputed_r_has_no_strength(self):
        assert strength_of(None) is None


class TestReading:
    def test_a_clear_positive_association(self):
        reading = _reading(_linear(200, slope=2.0, noise=10.0))
        assert reading["direction"] == "positive"
        assert reading["strength"] == "strong"
        assert reading["significant"] is True
        summary = " ".join(reading["summary"])
        assert "strong positive" in summary
        assert "higher x goes with higher y" in summary
        assert "each additional unit of x" in summary
        assert "more y" in summary
        assert "% of the variation in y" in summary
        assert "distinguishable from zero" in summary

    def test_a_negative_association_reads_as_lower(self):
        reading = _reading(_linear(200, slope=-3.0, noise=10.0))
        assert reading["direction"] == "negative"
        summary = " ".join(reading["summary"])
        assert "higher x goes with lower y" in summary
        assert "less y" in summary

    def test_noise_reads_as_no_relationship(self):
        rng = np.random.default_rng(4)
        df = pd.DataFrame({"x": rng.normal(size=3000), "y": rng.normal(size=3000)})
        reading = _reading(df)
        assert reading["strength"] == "negligible"
        assert reading["direction"] == "none"
        summary = " ".join(reading["summary"])
        assert "no meaningful linear relationship" in summary
        # No per-unit sentence: a slope indistinguishable from zero is not an effect.
        assert "each additional unit" not in summary

    def test_an_undetectable_slope_says_so_without_overclaiming(self):
        reading = _reading(_linear(12, slope=0.2, noise=20.0, seed=3))
        assert reading["significant"] is False
        summary = " ".join(reading["summary"])
        assert "do not distinguish the slope from zero" in summary
        assert f"{SIGNIFICANCE_LEVEL:.0%}" in " ".join(reading["summary"]) or "5%" in summary

    def test_caveats_that_always_apply(self):
        reading = _reading(_linear(200, slope=2.0, noise=10.0))
        caveats = " ".join(reading["caveats"])
        assert "not causation" in caveats
        assert "straight line" in caveats.lower()

    def test_small_sample_caveat(self):
        assert SMALL_SAMPLE == 30
        small = " ".join(_reading(_linear(12, slope=2.0, noise=1.0))["caveats"])
        large = " ".join(_reading(_linear(200, slope=2.0, noise=1.0))["caveats"])
        assert "n = 12" in small and "unstable" in small
        assert "unstable" not in large

    def test_exclusion_and_sampling_caveats(self):
        df = _linear(MAX_SCATTER_POINTS + 10, slope=1.0, noise=1.0)
        df.loc[:4, "y"] = np.nan
        caveats = " ".join(_reading(df)["caveats"])
        assert "5 rows were excluded" in caveats
        assert "sample of points" in caveats

    def test_group_and_size_caveats(self):
        df = _linear(60, slope=2.0, noise=1.0)
        df["g"] = ["a", "b"] * 30
        df["s"] = np.arange(60, dtype=float)
        caveats = " ".join(_reading(df, color_by="g", size="s")["caveats"])
        assert "pools all 2 groups of g" in caveats
        assert "Simpson" in caveats
        assert "Bubble area shows s" in caveats

    def test_next_steps_are_questions_the_chat_can_answer(self):
        df = _linear(60, slope=2.0, noise=1.0)
        df["g"] = ["a", "b"] * 30
        steps = _reading(df, color_by="g")["next_steps"]
        assert 1 <= len(steps) <= 3
        assert all(step["question"].endswith("?") and step["why"] for step in steps)
        assert any("across g" in step["question"] for step in steps)
        assert any("Spearman" in step["question"] for step in steps)

    def test_next_steps_do_not_suggest_more_predictors_for_nothing(self):
        rng = np.random.default_rng(4)
        df = pd.DataFrame({"x": rng.normal(size=3000), "y": rng.normal(size=3000)})
        steps = _reading(df)["next_steps"]
        assert not any("alongside x" in step["question"] for step in steps)

    def test_reads_an_uncomputed_fit_without_crashing(self):
        # A constant x has no slope; the reading must say so rather than fail.
        df = pd.DataFrame({"x": [1.0, 1.0, 1.0, 1.0], "y": [1.0, 2.0, 3.0, 4.0]})
        reading = _reading(df)
        assert reading["strength"] is None
        assert any("could not be computed" in s for s in reading["summary"])
