"""Provenance: the record that makes a reported number checkable.

Step 3 computes the figures and step 4 explains them. This module records what
actually ran — which operations, over how many rows, excluding how many and
why, with which library versions — and renders that record as a methods note a
researcher can read, attach to a paper, or use to reproduce the number
somewhere else.

Two things make the record worth keeping. The first is the denominator: a mean
over 442 of 480 rows is a different claim from a mean over 480, and only one of
them is true. The second is the sentence at the end of every note — that no
figure in it came from a language model. The pipeline is built so that claim is
true, and provenance is where it becomes checkable rather than merely asserted.

Nothing here calls a model. A methods note generated by the thing whose
trustworthiness it attests to would be worth nothing.
"""

from __future__ import annotations

import platform
from datetime import UTC, datetime
from typing import Any

import numpy as np
import pandas as pd
import scipy

from app.services.analysis_result import OperationResult
from app.services.analysis_stats import ALPHA, benjamini_hochberg

# ---------------------------------------------------------------------------
# The multiple-comparison family
# ---------------------------------------------------------------------------
#
# Which p-values in one answer get corrected together. Written down because
# both errors are silent: too narrow and the correction misses the tests that
# most need it, too broad and it double-adjusts values already corrected or
# drags diagnostics in beside substantive results.
#
# INCLUDED
#   * ``stats["p_value"]`` — an operation's primary test. That covers the
#     t-tests, ANOVA, Kruskal-Wallis, Mann-Whitney, Wilcoxon, chi-square, both
#     proportion z-tests, crosstab's chi-square, scatter_with_fit's slope test
#     and the survey module's Rao-Scott corrected chi-square.
#   * ``stats["f_p_value"]`` and ``stats["llr_p_value"]`` — the omnibus test of
#     a fitted regression. It is the same claim as an ANOVA's F, spelled
#     differently by the module that produces it, so leaving it out would be an
#     accident of naming rather than a decision.
#   * every ``p_value`` under ``stats["pairs"]`` — correlation_matrix has no
#     omnibus test, so its pairwise tests *are* its result. Six columns produce
#     fifteen of them, and that is exactly what this correction exists for:
#     unadjusted, six columns of pure noise yielded two "significant" pairs.
#
# EXCLUDED
#   * p-values already adjusted inside their own operation. granger_causality
#     runs Benjamini-Hochberg across its lags and anova's Tukey post-hoc
#     controls the family-wise rate across its pairs. The step-up procedure
#     assumes its inputs are p-values uniform under their nulls, which an
#     adjusted value is not — feeding one in would corrupt the correction for
#     every other test in the answer. Such an operation contributes nothing
#     rather than a number that is not a p-value.
#   * diagnostics. normality_test and stationarity_test ask whether a method
#     applies, not whether something is true of the data; so do the nested
#     Shapiro-Wilk, Levene, Ljung-Box, ADF and KPSS checks. Correcting them
#     against substantive tests inflates both families.
#   * a second presentation of a test already counted — Fisher's exact p beside
#     a 2x2 chi-square, ``naive_weighted_p_value`` beside the Rao-Scott
#     statistic (which is shown precisely as the wrong answer). Both are nested
#     rather than top-level, so the key rule already skips them.
#   * regression coefficient p-values, which live in the result *table* rather
#     than in ``stats``. They are conditional on one fitted model rather than
#     separate questions asked of the dataset, and a ten-regressor fit would
#     otherwise contribute eleven "tests" and swamp every other result in the
#     answer.

# Checked in order; the first one present is the operation's primary test.
_PRIMARY_P_VALUE_KEYS = ("p_value", "f_p_value", "llr_p_value")

# correlation_matrix's per-pair tests. The only top-level "pairs" in any
# stats payload; Tukey's live under "post_hoc" and Granger's under "lags".
_PAIRWISE_KEY = "pairs"

# Operations held out of the family on purpose, so the exclusion survives
# someone later adding a top-level p_value to one of them.
_OUTSIDE_THE_FAMILY = frozenset(
    {
        "granger_causality",  # adjusts across its own lags already
        "normality_test",  # diagnostic
        "stationarity_test",  # diagnostic
    }
)


def environment() -> dict[str, str]:
    """The versions that produced these numbers.

    A statistic is only reproducible against the library that computed it;
    scipy has changed default corrections between minor versions before.
    """
    return {
        "python": platform.python_version(),
        "pandas": pd.__version__,
        "numpy": np.__version__,
        "scipy": scipy.__version__,
    }


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _family_members(result: OperationResult) -> list[tuple[str, str, float]]:
    """The (label, test, p-value) triples one result contributes to the family.

    The membership rule is written out above :data:`_PRIMARY_P_VALUE_KEYS`.
    """
    if result.op in _OUTSIDE_THE_FAMILY:
        return []

    for key in _PRIMARY_P_VALUE_KEYS:
        value = result.stats.get(key)
        if _is_number(value):
            return [(result.label, str(result.stats.get("test", result.op)), float(value))]

    pairs = result.stats.get(_PAIRWISE_KEY)
    if not isinstance(pairs, list):
        return []
    method = str(result.stats.get("method", "pearson"))
    return [
        (
            f"{result.label} — {pair.get('x')} vs {pair.get('y')}",
            f"{method} correlation of {pair.get('x')} and {pair.get('y')}",
            float(pair["p_value"]),
        )
        for pair in pairs
        if isinstance(pair, dict) and _is_number(pair.get("p_value"))
    ]


def multiple_comparison_adjustment(results: list[OperationResult]) -> dict[str, Any] | None:
    """Adjust the p-values across every test in one answer, or None if there is one.

    Returns None for a single test — there is nothing to correct — and for an
    analysis that ran no tests at all. What counts as a test is the rule written
    out above :data:`_PRIMARY_P_VALUE_KEYS`; note that one operation can
    contribute many members (a correlation matrix over six columns contributes
    fifteen) or none (a diagnostic, or an operation that has already corrected
    itself).
    """
    tests = [member for result in results for member in _family_members(result)]
    if len(tests) < 2:
        return None

    adjusted = benjamini_hochberg([p_value for _, _, p_value in tests])
    return {
        "method": "Benjamini-Hochberg",
        "controls": "false discovery rate",
        "n_tests": len(tests),
        "note": (
            f"{len(tests)} tests were run against one dataset, so each p-value is "
            f"reported alongside a value adjusted for how many were run."
        ),
        "tests": [
            {
                "label": label,
                "test": test_name,
                "p_value": p_value,
                "p_value_adjusted": adjusted_p,
                "significant_at_0.05_after_adjustment": (
                    None if adjusted_p is None else bool(adjusted_p < ALPHA)
                ),
            }
            for (label, test_name, p_value), adjusted_p in zip(tests, adjusted, strict=True)
        ],
    }


def build_provenance(
    *,
    question: str,
    spec: dict[str, Any],
    results: list[OperationResult],
    df: pd.DataFrame,
    filename: str | None = None,
) -> dict[str, Any]:
    """Assemble the full record behind one answer."""
    planned = spec.get("operations", [])
    operations = []
    for index, result in enumerate(results):
        # Keyed on the spec index the result carries, not on its position in
        # this list: execute_spec drops failed operations, so after the first
        # failure a positional lookup attributes every remaining result to the
        # wrong plan entry. This record's whole purpose is letting a researcher
        # rerun the analysis, and the wrong parameters are worse than none.
        spec_index = result.spec_index
        params = planned[spec_index].get("params", {}) if 0 <= spec_index < len(planned) else {}
        operations.append(
            {
                "index": index,
                "spec_index": spec_index,
                "op": result.op,
                "label": result.label,
                "params": params,
                "n": result.n,
                "n_excluded": result.n_excluded,
                "notes": list(result.notes),
                "statistics": dict(result.stats),
            }
        )

    provenance: dict[str, Any] = {
        "question": question,
        "generated_at": datetime.now(UTC).isoformat(),
        "rationale": str(spec.get("rationale") or ""),
        "dataset": {
            "filename": filename,
            "rows": int(len(df)),
            "columns": int(len(df.columns)),
        },
        "filter": spec.get("filter"),
        "operations": operations,
        "environment": environment(),
    }
    adjustment = multiple_comparison_adjustment(results)
    if adjustment is not None:
        provenance["multiple_comparisons"] = adjustment
    provenance["methods_note"] = render_methods_note(provenance)
    return provenance


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _format_number(value: Any) -> str:
    if value is None:
        return "not computed"
    if isinstance(value, float):
        return f"{value:.4g}"
    return str(value)


def _render_statistics(statistics: dict[str, Any]) -> list[str]:
    """The test, its statistic, its effect size, and its interval — in prose."""
    if not statistics:
        return []

    lines: list[str] = []
    test_name = statistics.get("test")
    if test_name:
        pieces = [str(test_name)]
        if statistics.get("statistic") is not None:
            pieces.append(f"statistic = {_format_number(statistics['statistic'])}")
        for key in ("dof", "df_between", "df_within"):
            if statistics.get(key) is not None:
                pieces.append(f"{key} = {_format_number(statistics[key])}")
        if statistics.get("p_value") is not None:
            pieces.append(f"p = {_format_number(statistics['p_value'])}")
        lines.append("   " + ", ".join(pieces) + ".")

    effect = statistics.get("effect_size")
    if isinstance(effect, dict) and effect.get("value") is not None:
        rendered = f"   Effect size: {effect.get('name')} = {_format_number(effect['value'])}"
        if effect.get("magnitude"):
            rendered += f" ({effect['magnitude']} by Cohen's conventional cutoffs)"
        lines.append(rendered + ".")

    ci = statistics.get("confidence_interval")
    if isinstance(ci, dict) and ci.get("low") is not None:
        level = int(float(ci.get("level", 0.95)) * 100)
        of = ci.get("of", "the estimate")
        lines.append(
            f"   {level}% CI for {of}: [{_format_number(ci['low'])}, {_format_number(ci['high'])}]."
        )

    checks = statistics.get("assumptions") or []
    rendered_checks = [
        f"{check['name']} — {'pass' if check['passed'] else 'FAIL' if check['passed'] is False else 'not evaluated'}"
        f": {check['detail']}"
        for check in checks
        if isinstance(check, dict)
    ]
    if rendered_checks:
        lines.append("   Assumptions: " + "; ".join(rendered_checks) + ".")
    return lines


def render_methods_note(provenance: dict[str, Any]) -> str:
    """Render the provenance record as a methods section, in markdown.

    Deterministic by construction: this function never calls a model, so the
    note describing the analysis is not itself something to take on faith.
    """
    dataset = provenance.get("dataset", {})
    filename = dataset.get("filename") or "the uploaded file"
    lines = [
        "## Methods",
        "",
        f"**Question.** {provenance.get('question', '')}",
        "",
        f"**Data.** `{filename}` — {dataset.get('rows', 0)} rows, "
        f"{dataset.get('columns', 0)} columns. Every operation below ran over the "
        f"full dataset, not a sample.",
    ]

    spec_filter = provenance.get("filter")
    if spec_filter:
        value = spec_filter.get("value")
        lines += [
            "",
            f"**Filter.** Rows were restricted to `{spec_filter.get('column')} "
            f"{spec_filter.get('operator')}"
            f"{'' if value is None else f' {value!r}'}` before any operation ran.",
        ]

    if provenance.get("rationale"):
        lines += ["", f"**Approach.** {provenance['rationale']}"]

    operations = provenance.get("operations", [])
    lines += ["", f"**Analysis.** {len(operations)} operation(s) were executed:", ""]
    for operation in operations:
        excluded = operation.get("n_excluded", 0)
        denominator = f"n = {operation.get('n', 0)}"
        if excluded:
            denominator += f" ({excluded} excluded for missing values)"
        lines.append(
            f"{operation['index'] + 1}. **{operation['label']}** — `{operation['op']}`"
            f"({_render_params(operation.get('params', {}))}); {denominator}."
        )
        lines += _render_statistics(operation.get("statistics", {}))
        for note in operation.get("notes", []):
            lines.append(f"   Note: {note}")

    adjustment = provenance.get("multiple_comparisons")
    if adjustment:
        lines += [
            "",
            f"**Multiple comparisons.** {adjustment['n_tests']} hypothesis tests were run "
            f"against this dataset. P-values adjusted by the {adjustment['method']} "
            f"procedure, which controls the {adjustment['controls']}:",
            "",
        ]
        for entry in adjustment["tests"]:
            lines.append(
                f"- {entry['label']}: p = {_format_number(entry['p_value'])}, "
                f"adjusted p = {_format_number(entry['p_value_adjusted'])}"
            )

    env = provenance.get("environment", {})
    lines += [
        "",
        "**Software.** "
        + ", ".join(
            [
                f"Python {env.get('python', '?')}",
                f"pandas {env.get('pandas', '?')}",
                f"numpy {env.get('numpy', '?')}",
                f"scipy {env.get('scipy', '?')}",
            ]
        )
        + ".",
        "",
        "**Provenance.** Every figure above was computed from the uploaded file by "
        "deterministic code. No value was produced by a language model; the model "
        "selected which operations to run and wrote the interpretation of the results.",
    ]
    return "\n".join(lines)


def _render_params(params: dict[str, Any]) -> str:
    return ", ".join(f"{key}={value!r}" for key, value in params.items())
